[2024-10-28T16:22:26.494+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: create_ddl_dag.create_schema manual__2024-10-28T16:22:25.872279+00:00 [queued]>
[2024-10-28T16:22:26.504+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: create_ddl_dag.create_schema manual__2024-10-28T16:22:25.872279+00:00 [queued]>
[2024-10-28T16:22:26.505+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-28T16:22:26.505+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-10-28T16:22:26.506+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-28T16:22:26.521+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_schema> on 2024-10-28 16:22:25.872279+00:00
[2024-10-28T16:22:26.527+0000] {standard_task_runner.py:55} INFO - Started process 2546 to run task
[2024-10-28T16:22:26.529+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_ddl_dag', 'create_schema', 'manual__2024-10-28T16:22:25.872279+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/create_bronze_ddl.py', '--cfg-path', '/tmp/tmpefvr5iz8']
[2024-10-28T16:22:26.530+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask create_schema
[2024-10-28T16:22:26.593+0000] {task_command.py:388} INFO - Running <TaskInstance: create_ddl_dag.create_schema manual__2024-10-28T16:22:25.872279+00:00 [running]> on host 351cc7a93433
[2024-10-28T16:22:26.625+0000] {abstractoperator.py:613} ERROR - Exception rendering Jinja template for task 'create_schema', field 'sql'. Template: '/opt/***/sql/create_bronze.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/create_bronze.sql
[2024-10-28T16:22:26.627+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/create_bronze.sql
[2024-10-28T16:22:26.636+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=create_ddl_dag, task_id=create_schema, execution_date=20241028T162225, start_date=20241028T162226, end_date=20241028T162226
[2024-10-28T16:22:26.651+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task create_schema (/opt/airflow/sql/create_bronze.sql; 2546)
[2024-10-28T16:22:26.702+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-28T16:22:26.729+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
